
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 20:00:37 EST 2019
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 8;
  public static final int PLUS = 4;
  public static final int RBRACE = 14;
  public static final int RPAREN = 3;
  public static final int SEMI = 16;
  public static final int IN = 12;
  public static final int POW = 10;
  public static final int VARIABLE = 18;
  public static final int LPAREN = 2;
  public static final int LBRACE = 13;
  public static final int COMMA = 15;
  public static final int FLOAT = 19;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int LET = 11;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 17;
  public static final int MUL = 6;
}

